groupVoice:
  - config:
      active: true
      affiliated: false
      parrot: false
    name: SUPERGROUP
    source:
      slot: 1
      tgid: 65534
  - config:
      active: true
      affiliated: false
      parrot: false
    name: ANNOUNCE
    source:
      slot: 1
      tgid: 65534
  - config:
      active: true
      affiliated: false
      parrot: false
    name: PARROT
    source:
      slot: 1
      tgid: 9990
  - config:
      active: true
      affiliated: false
      parrot: false
    name: null
    source:
      slot: 1
      tgid: 3149
  - config:
      active: true
      affiliated: false
      parrot: false
    name: null
    source:
      slot: 1
      tgid: 31490
  - config:
      active: true
      affiliated: false
      parrot: false
    name: null
    source:
      slot: 1
      tgid: 31491
  - config:
      active: true
      affiliated: false
      parrot: false
    name: null
    source:
      slot: 1
      tgid: 31492
  - config:
      active: true
      affiliated: false
      parrot: false
    name: null
    source:
      slot: 1
      tgid: 31493
  - config:
      active: true
      affiliated: false
      parrot: false
    name: null
    source:
      slot: 1
      tgid: 31494
  - config:
      active: true
      affiliated: false
      parrot: false
    name: null
    source:
      slot: 1
      tgid: 31495
  - config:
      active: true
      affiliated: false
      parrot: false
    name: null
    source:
      slot: 1
      tgid: 31496
  - config:
      active: true
      affiliated: false
      parrot: false
    name: null
    source:
      slot: 1
      tgid: 31497
  - config:
      active: true
      affiliated: false
      parrot: false
    name: null
    source:
      slot: 1
      tgid: 31498
  - config:
      active: true
      affiliated: false
      parrot: false
    name: null
    source:
      slot: 1
      tgid: 31499
