daemon: true
log:
  disableNonAuthoritiveLogging: false
  displayLevel: 1
  fileLevel: 2
  useSyslog: false
  filePath: /var/log/dvmhost
  activityFilePath: /var/log/dvmhost
  fileRoot: DVM-CONV1
network:
  enable: false
  id: 1234567
  address: 0.0.0.0
  port: 62031
  password: Passw0rd1
  encrypted: false
  presharedKey: 000102030405060708090A0B0C0D0E0F000102030405060708090A0B0C0D0E0F
  jitter: 360
  slot1: true
  slot2: true
  updateLookups: true
  saveLookups: true
  allowActivityTransfer: true
  allowDiagnosticTransfer: true
  allowStatusTransfer: true
  debug: false
  restEnable: false
  restAddress: 127.0.0.1
  restPort: 9990
  restSsl: false
  restSslCertificate: web.crt
  restSslKey: web.key
  restPassword: Passw0rd1
  restDebug: false
protocols:
  dmr:
    enable: false
    beacons:
      enable: false
      interval: 60
      duration: 3
    control:
      dedicated: false
      enable: false
      slot: 1
      disableGrantSourceIdCheck: false
    ignoreAffiliationCheck: false
    embeddedLCOnly: false
    dumpTAData: true
    dumpDataPacket: false
    repeatDataPacket: true
    dumpCsbkData: false
    verifyReg: false
    disableUnitRegTimeout: false
    nRandWait: 8
    backOff: 1
    callHang: 5
    txHang: 8
    silenceThreshold: 21
    frameLossThreshold: 2
    queueSize: 31
    verbose: true
    debug: false
  p25:
    enable: true
    tduPreambleCount: 6
    control:
      enable: false
      ackRequests: true
      dedicated: false
      broadcast: false
      interval: 300
      duration: 1
      disableTSDUMBF: false
      enableTimeDateAnn: true
      disableGrantSourceIdCheck: false
      redundantImmediate: true
      redundantGrantTransmit: false
    controlOnly: false
    disableNetworkHDU: false
    disableNetworkGrant: false
    ignoreAffiliationCheck: false
    inhibitUnauthorized: false
    legacyGroupGrnt: true
    legacyGroupReg: false
    convNetGrantDemand: false
    demandUnitRegForRefusedAff: false
    verifyAff: false
    verifyReg: false
    disableUnitRegTimeout: false
    requireLLAForReg: false
    dumpDataPacket: false
    repeatDataPacket: true
    dumpTsbkData: false
    callHang: 5
    noStatusAck: false
    noMessageAck: true
    unitToUnitAvailCheck: true
    allowExplicitSourceId: true
    sndcpSupport: false
    silenceThreshold: 124
    frameLossThreshold: 6
    queueSize: 12
    verbose: true
    debug: false
  nxdn:
    enable: false
    control:
      enable: false
      dedicated: false
      broadcast: true
      interval: 300
      duration: 1
      disableGrantSourceIdCheck: false
    ignoreAffiliationCheck: false
    verifyAff: false
    verifyReg: false
    disableUnitRegTimeout: false
    dumpRcchData: false
    callHang: 5
    silenceThreshold: 14
    frameLossThreshold: 4
    queueSize: 31
    verbose: true
    debug: false
system:
  identity: FF-CO1
  timeout: 180
  duplex: true
  simplexSameFrequency: false
  modeHang: 10
  fixedMode: true
  rfTalkgroupHang: 10
  activeTickDelay: 5
  idleTickDelay: 5
  localTimeOffset: -6
  disableWatchdogOverflow: false
  info:
    latitude: 0
    longitude: 0
    height: 1
    power: 1
    location: Earth
  config:
    authoritative: true
    supervisor: true
    channelId: 5
    channelNo: 0
    controlCh:
      restAddress:
      restPort: 0
      restPassword: Passw0rd1
      restSsl: false
      notifyEnable: false
      presence: 120
    voiceChNo: []
    secure:
      key: 000102030405060708090A0B0C0D0E0F
    colorCode: 1
    nac: F7E
    ran: 1
    pSuperGroup: FFFE
    announcementGroup: FFFE
    dmrNetId: 1
    netId: BB800
    sysId: 001
    rfssId: 1
    siteId: 1
  cwId:
    enable: false
    time: 15
    callsign: NIFOG
  modem:
    protocol:
      type: uart
      mode: air
      uart:
        port: /dev/ttyAMA0
        speed: 115200
    rxInvert: false
    txInvert: false
    pttInvert: false
    dcBlocker: true
    cosLockout: false
    fdmaPreamble: 120
    dmrRxDelay: 7
    p25CorrCount: 8
    dmrFifoLength: 560
    p25FifoLength: 522
    nxdnFifoLength: 538
    hotspot:
      dmrDiscBWAdj: 0
      dmrPostBWAdj: 0
      p25DiscBWAdj: 0
      p25PostBWAdj: 0
      nxdnDiscBWAdj: 0
      nxdnPostBWAdj: 0
      adfGainMode: 2
      afcEnable: true
      afcKI: 13
      afcKP: 5
      afcRange: 1
      txTuning: 0
      rxTuning: 0
    repeater:
      dmrSymLvl3Adj: 0
      dmrSymLvl1Adj: 0
      p25SymLvl3Adj: 0
      p25SymLvl1Adj: 0
      nxdnSymLvl3Adj: 0
      nxdnSymLvl1Adj: 0
    softpot:
      rxCoarse: 127
      rxFine: 127
      txCoarse: 127
      txFine: 127
      rssiCoarse: 127
      rssiFine: 127
    rxDCOffset: 0
    txDCOffset: 0
    rxLevel: 50
    txLevel: 50
    rssiMappingFile: /etc/dvmhost/configs/RSSI.dat
    packetPlayoutTime: 10
    disableOFlowReset: false
    ignoreModemConfigArea: false
    dumpModemStatus: false
    trace: false
    debug: false
  iden_table:
    file: /etc/dvmhost/configs/iden_table.dat
    time: 30
  radio_id:
    file: /etc/dvmhost/configs/rid_acl.dat
    time: 10
    acl: false
  talkgroup_id:
    file: /etc/dvmhost/configs/talkgroup_rules.yml
    time: 10
    acl: false
